# tâche 4 

François Clinquart - 59602100 

## Importation des modules nécessaire

In [1]:
!pip install mp-api --upgrade
import numpy as np
from mp_api.client import MPRester
#from pymatgen.ext.matproj import MPRester
from pymatgen.core.operations import SymmOp
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from pymatgen.electronic_structure.plotter import BSPlotter
from pymatgen.phonon.plotter import PhononBSPlotter
from jupyter_jsmol.pymatgen import quick_view
from lmapr1492 import plot_brillouin_zone, get_plot_bs, get_plot_dos, get_plot_bs_and_dos, get_branch_wavevectors
from plotly.subplots import make_subplots
import plotly.graph_objects as go

Defaulting to user installation because normal site-packages is not writeable

[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python3.9 -m pip install --upgrade pip


## télechargement des données 

In [4]:
mp_key = "WsY2TKc5UWjyvSj20HzKrEQE38dWtvzf" ## Ma clef API semble avoir changer depuis que je vous l'ai donnée dans la tâche 3 
mp_id = "mp-2894"

In [5]:
with MPRester(mp_key) as m:
    prim_struc = m.get_structure_by_material_id(mp_id)
    
spacegroup_analyzer = SpacegroupAnalyzer(prim_struc)
conv_struc = spacegroup_analyzer.get_conventional_standard_structure()



Retrieving MaterialsDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

In [6]:
i_atom = 7
i_symmop = 2

view = quick_view(prim_struc, "packed", conventional = True)
display(view)
view.script('select antimony; color lightsalmon')
view.script('select sodium; color gold')
view.script('select lithium; color palegreen')
view.script('draw SYMOP ' + str(i_symmop) + ' {atomno = ' + str(i_atom) + '}')

JsmolView(layout=Layout(align_self='stretch', height='400px'))

# Delivrable
- Déterminer les vecteurs de bases du réseaux direct 
- Déterminer les vecteurs de bases du réseaux réciproque
- type de maille, son système cristallin
- son groupe ponctuel.


In [7]:

lattice = spacegroup_analyzer.get_lattice_type()
parameters = conv_struc.lattice.parameters

a, b, c, alpha, beta, gamma = parameters
reciprocal_lattice = conv_struc.lattice.reciprocal_lattice

a_r, b_r, c_r = reciprocal_lattice.abc
alpha_r, beta_r, gamma_r = reciprocal_lattice.angles

# Affichage des 6 paramètres du réseau réciproque

print("Réseaux direct \n")
print("a :", a)
print("b :", b)
print("c :", c)
print("Angle alpha :", alpha)
print("Angle beta :", beta)
print("Angle gamma :", gamma)
print(10*"-")
print("Réseaux reciproque \n")
print(" a :", a_r)
print(" b :", b_r)
print(" c :", c_r)
print("Angle alpha :", alpha_r)
print("Angle beta  :", beta_r)
print("Angle gamma :", gamma_r)



Réseaux direct 

a : 6.471973597179354
b : 6.471973597179354
c : 6.471973597179354
Angle alpha : 90.0
Angle beta : 90.0
Angle gamma : 90.0
----------
Réseaux reciproque 

 a : 0.9708298732735796
 b : 0.9708298732735796
 c : 0.9708298732735796
Angle alpha : 90.00000000000001
Angle beta  : 90.00000000000001
Angle gamma : 90.00000000000001


In [8]:
reciprocal_lattice_vectors = prim_struc.lattice.reciprocal_lattice.matrix
print(reciprocal_lattice_vectors)

[[ 1.58535868e+00 -5.60508591e-01  0.00000000e+00]
 [ 4.24278886e-09  1.68152664e+00  0.00000000e+00]
 [-7.92679341e-01 -5.60509024e-01  1.37296067e+00]]


In [9]:

print("Type de maille :", lattice_type)

NameError: name 'lattice_type' is not defined

In [ ]:
print("Système cristallin :", spacegroup_analyzer.get_crystal_system())

In [ ]:
print("groupe ponctuel :" ,spacegroup_analyzer.get_point_group_symbol())
