# tâche 5 
- François Clinquart 
- Noma = `59602100`

## Importation des Modules et packages nécéssaires 

In [113]:
import numpy as np
from mp_api.client import MPRester
from pymatgen.core.operations import SymmOp
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from pymatgen.electronic_structure.plotter import BSPlotter
from pymatgen.phonon.plotter import PhononBSPlotter
from jupyter_jsmol.pymatgen import quick_view
from lmapr1492 import plot_brillouin_zone, get_plot_bs, get_plot_dos, get_plot_bs_and_dos, get_branch_wavevectors
from plotly.subplots import make_subplots
import plotly.graph_objects as go

## Aujout pas utiles
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D


# Mon Matériaux 
Il s'agit d'un Cristal cubique de groupe ponctuel : -43m



In [114]:
mp_key = "ER5V8i0JUw7k31Nk5IpkvogP61BDz9cw"
mp_id = "mp-2894" #ScSnAu

In [115]:
with MPRester(mp_key) as m:
    prim_struc = m.get_structure_by_material_id(mp_id)
    
spacegroup_analyzer = SpacegroupAnalyzer(prim_struc)
conv_struc = spacegroup_analyzer.get_conventional_standard_structure()

Retrieving MaterialsDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

In [116]:
# Crée une vue rapide de la structure avec la maille conventionnelle
view = quick_view(prim_struc, "packed", conventional=True)
display(view)

# Applique les couleurs aux différents types d'atomes
view.script('select Sc; color lightsalmon')
view.script('select Sn; color gold')
view.script('select Au; color palegreen')

# Dessine l'opération de symétrie
view.script('draw SYMOP ' + str(i_symmop) + ' {atomno = ' + str(i_atom) + '}')


JsmolView(layout=Layout(align_self='stretch', height='400px'))

# Delivrable
pour étudier l’effet de 3 éléments de symétrie différents (pas l’identité) chacun pour 1 atome différent 

In [144]:
sym = spacegroup_analyzer.get_symmetry_operations()
#print(len(sym)) 48 opération 


s1 = sym[26]
s2 = sym[29] 



#Structure Finale dans la maille conventionnelle 
#Source: the materials project, je choisi des atomes en rergardant la figure du haut 

Sc : list = [0,0,1/2]
Sn : list = [1/2,0,1/2]
Au : list = [1/4,1/4,1/4]
### Affichage des opérateurs    
for i in range(10,20):
    print(sym[i])

Rot:
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
tau
[0. 0. 0.]
-------------
Rot:
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
tau
[0. 0. 0.]
Rot:
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
tau
[0. 0. 0.]
Rot:
[[-1. -1. -1.]
 [ 0.  0.  1.]
 [ 0.  1.  0.]]
tau
[0. 0. 0.]
Rot:
[[-1. -1. -1.]
 [ 0.  0.  1.]
 [ 0.  1.  0.]]
tau
[0. 0. 0.]
Rot:
[[ 1.  0.  0.]
 [-1. -1. -1.]
 [ 0.  0.  1.]]
tau
[0. 0. 0.]
Rot:
[[ 1.  0.  0.]
 [-1. -1. -1.]
 [ 0.  0.  1.]]
tau
[0. 0. 0.]
Rot:
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
tau
[0. 0. 0.]
Rot:
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
tau
[0. 0. 0.]
Rot:
[[-1. -1. -1.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
tau
[0. 0. 0.]
Rot:
[[-1. -1. -1.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
tau
[0. 0. 0.]


### Opération de Symmétrie pour le Scandium 

In [126]:
s1_type : str = " Rotation autour de l'atome d'or (1/4, 1/4, 1/4) parallèle à l'axe c "
print(70*'-')
print("la matrice associé à l'opération de symmétrie est \n" )
print(s1)
print("\n Il s'agit d'une opération d'ordre un consevant la chiralité")
print("\n Il s'agit d'une opération de :", s1_type)
print("\n le déterminant de la matrice vaut 1")
print(70*'_')
print("coordonné de l'atome de {} avant l'opération : {}".format('Cesium',str(Sc)))
print("coordonné de l'atome de {} après l'opération : {}".format('Cesium',str(s1.operate(Sc))))
print(70*'_')
print(70*'-')



----------------------------------------------------------------------
la matrice associé à l'opération de symmétrie est 

Rot:
[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
tau
[0. 0. 0.]

 Il s'agit d'une opération d'ordre un consevant la chiralité

 Il s'agit d'une opération de :  Rotation autour de l'atome d'or (1/4, 1/4, 1/4) parallèle à l'axe c 

 le déterminant de la matrice vaut 1
______________________________________________________________________
coordonné de l'atome de Cesium avant l'opération : [0, 0, 0.5]
coordonné de l'atome de Cesium après l'opération : [0.  0.5 0. ]
______________________________________________________________________
----------------------------------------------------------------------


In [119]:
view1 = quick_view(conv_struc, conventional = "True")
display(view1)
view1.script("draw SYMOP 27 {atomno=1}")





JsmolView(layout=Layout(align_self='stretch', height='400px'))

### Opération de symmétrie pour l'étain

In [120]:
s2_type : str = "plan mirroir xy"
print(70*'-')
print("la matrice associé à l'opération de symmétrie est \n" )
print(s2)
print("\n Il s'agit d'une opération d'ordre un")
print("\n le déterminant vaut -1")
print("\n Il s'agit d'une opération de :", s2_type)
print(70*'_')
print("coordonné de l'atome de {} avant l'opération : {}".format('étain',str(Sn)))
print("coordonné de l'atome de {} après l'opération : {}".format('étain',str(s2.operate(Sn))))
print(70*'_')
print(70*'-')

----------------------------------------------------------------------
la matrice associé à l'opération de symmétrie est 

Rot:
[[ 0.  1.  0.]
 [-1. -1. -1.]
 [ 0.  0.  1.]]
tau
[0. 0. 0.]

 Il s'agit d'une opération d'ordre un

 le déterminant vaut -1

 Il s'agit d'une opération de : plan mirroir xy
______________________________________________________________________
coordonné de l'atome de étain avant l'opération : [0.5, 0.5, 0]
coordonné de l'atome de étain après l'opération : [ 0.5 -1.   0. ]
______________________________________________________________________
----------------------------------------------------------------------


In [124]:
view1 = quick_view(conv_struc, conventional = "True")
display(view1)
view1.script("draw SYMOP 30 {atomno=2}") ## + 1 dans le display car liste 


JsmolView(layout=Layout(align_self='stretch', height='400px'))

### Opération de symmétrie pour l' Or 

In [149]:
s4_type : str = 'Opération de Roto-inversion (----)'
print(70*'-')
print("la matrice associé à l'opération de symmétrie est \n" )
print(sym[43])
print("\n Il s'agit d'une opération d'ordre deux inversant la chiralité")
print("\n Il s'agit d'une opération de :", s4_type)
print("\n le déterminant de la matrice vaut 0")
print("/!\ pas sur de celle-ci")
print(70*'_')
print("coordonné de l'atome de {} avant l'opération : {}".format('Cesium',str(Au)))
print("coordonné de l'atome de {} avant l'opération : {}".format('Cesium',str(sym[43].operate(Au))))
print(70*'_')
print(70*'-')

----------------------------------------------------------------------
la matrice associé à l'opération de symmétrie est 

Rot:
[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]
tau
[0. 0. 0.]

 Il s'agit d'une opération d'ordre deux inversant la chiralité

 Il s'agit d'une opération de : Opération de Roto-inversion (----)

 le déterminant de la matrice vaut 0
/!\ pas sur de celle-ci
______________________________________________________________________
coordonné de l'atome de Cesium avant l'opération : [0.25, 0.25, 0.25]
coordonné de l'atome de Cesium avant l'opération : [0.25 0.25 0.25]
______________________________________________________________________
----------------------------------------------------------------------


In [148]:
view1 = quick_view(conv_struc, conventional = "True")
display(view1)
view1.script("draw SYMOP 44 {atomno=3}")


JsmolView(layout=Layout(align_self='stretch', height='400px'))