# tâche 5 
- François Clinquart 
- Noma = `59602100`

## Importation des Modules et packages nécéssaires 

In [1]:
import numpy as np
from mp_api.client import MPRester
from pymatgen.core.operations import SymmOp
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from pymatgen.electronic_structure.plotter import BSPlotter
from pymatgen.phonon.plotter import PhononBSPlotter
from jupyter_jsmol.pymatgen import quick_view
from lmapr1492 import plot_brillouin_zone, get_plot_bs, get_plot_dos, get_plot_bs_and_dos, get_branch_wavevectors
from plotly.subplots import make_subplots
import plotly.graph_objects as go
## IMPORTATION IMPORTANTE
from pymatgen.analysis.diffraction.xrd import XRDCalculator

## Aujout pas utiles
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D


# Mon Matériaux 
Il s'agit d'un Cristal cubique de groupe ponctuel : -43m



In [2]:
mp_key = "ER5V8i0JUw7k31Nk5IpkvogP61BDz9cw"
mp_id = "mp-2894" #ScSnAu

In [3]:
with MPRester(mp_key) as m:
    prim_struc = m.get_structure_by_material_id(mp_id)
    
spacegroup_analyzer = SpacegroupAnalyzer(prim_struc)
conv_struc = spacegroup_analyzer.get_conventional_standard_structure()

Retrieving MaterialsDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

In [8]:
# Crée une vue rapide de la structure avec la maille conventionnelle
view = quick_view(prim_struc, "packed", conventional=True)
display(view)

# Applique les couleurs aux différents types d'atomes
view.script('select Sc; color lightsalmon')
view.script('select Sn; color gold')
view.script('select Au; color palegreen')




JsmolView(layout=Layout(align_self='stretch', height='400px'))

# Delivrable
pour étudier l’effet de 3 éléments de symétrie différents (pas l’identité) chacun pour 1 atome différent 

In [32]:
sym = spacegroup_analyzer.get_symmetry_operations()  
#une liste contenant les 48 opérateurs de symmétrie (Matrice Orthogonale)
#print(len(sym)) 48 opération 


s1 = sym[26]
s2 = sym[29] 



#Structure Finale dans la maille conventionnelle 
#Source: the materials project, je choisi des atomes en rergardant la figure du haut 

Sc : list = [0,0,1/2]
Sn : list = [1/2,0,1/2]
Au : list = [1/4,1/4,1/4]
### Affichage des opérateurs afin des choisir un opérateur interresant    
for i in range(10,20):
    print(sym[i])

Rot:
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
tau
[0. 0. 0.]
Rot:
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
tau
[0. 0. 0.]
Rot:
[[-1. -1. -1.]
 [ 0.  0.  1.]
 [ 0.  1.  0.]]
tau
[0. 0. 0.]
Rot:
[[-1. -1. -1.]
 [ 0.  0.  1.]
 [ 0.  1.  0.]]
tau
[0. 0. 0.]
Rot:
[[ 1.  0.  0.]
 [-1. -1. -1.]
 [ 0.  0.  1.]]
tau
[0. 0. 0.]
Rot:
[[ 1.  0.  0.]
 [-1. -1. -1.]
 [ 0.  0.  1.]]
tau
[0. 0. 0.]
Rot:
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
tau
[0. 0. 0.]
Rot:
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
tau
[0. 0. 0.]
Rot:
[[-1. -1. -1.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
tau
[0. 0. 0.]
Rot:
[[-1. -1. -1.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
tau
[0. 0. 0.]


### Opération de Symmétrie pour le Scandium 

In [38]:
s1_type : str = " Rotation d'ordre 2 autour de l'atome d'or (1/4, 1/4, 1/4) parallèle à l'axe c "
print(70*'-')
print("la matrice associé à l'opération de symmétrie est \n" )
print(s1)
print("\n Il s'agit d'une opération d'ordre un consevant la chiralité")
print("\n Il s'agit d'une opération de :", s1_type)
print("\n le déterminant de la matrice vaut 1")
print(70*'_')
print("coordonné de l'atome de {} avant l'opération : {}".format('Scandium',str(Sc)))
print("coordonné de l'atome de {} après l'opération : {}".format('Scandium',str([0.5,0.5,0.5])))
print(70*'_')
print(70*'-')



----------------------------------------------------------------------
la matrice associé à l'opération de symmétrie est 

Rot:
[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
tau
[0. 0. 0.]

 Il s'agit d'une opération d'ordre un consevant la chiralité

 Il s'agit d'une opération de :  Rotation d'ordre 2 autour de l'atome d'or (1/4, 1/4, 1/4) parallèle à l'axe c 

 le déterminant de la matrice vaut 1
______________________________________________________________________
coordonné de l'atome de Scandium avant l'opération : [0, 0, 0.5]
coordonné de l'atome de Scandium après l'opération : [0.5, 0.5, 0.5]
______________________________________________________________________
----------------------------------------------------------------------


In [17]:
view1 = quick_view(conv_struc, conventional = "True")
display(view1)
view1.script("draw SYMOP 27 {atomno=1}")





JsmolView(layout=Layout(align_self='stretch', height='400px'))

### Opération de symmétrie pour l'étain

In [36]:
s2_type : str = "plan mirroir xy"
print(70*'-')
print("la matrice associé à l'opération de symmétrie est \n" )
print(s2)
print("\n Il s'agit d'une opération d'ordre un")
print("\n le déterminant vaut -1") # donc on a le choix entre roto-inversion, inversion et reflexion. 
print("\n Il s'agit d'une opération de :", s2_type)
print(70*'_')
print("coordonné de l'atome de {} avant l'opération : {}".format('étain',str(Sn)))
print("coordonné de l'atome de {} après l'opération : {}".format('étain',str([0,0.5,0.5])))
# je ne comprend ce que fait s2.operate(Sn) elle n'applique pas la bonne opération 
print(70*'_')
print(70*'-')

----------------------------------------------------------------------
la matrice associé à l'opération de symmétrie est 

Rot:
[[ 0.  1.  0.]
 [-1. -1. -1.]
 [ 0.  0.  1.]]
tau
[0. 0. 0.]

 Il s'agit d'une opération d'ordre un

 le déterminant vaut -1

 Il s'agit d'une opération de : plan mirroir xy
______________________________________________________________________
coordonné de l'atome de étain avant l'opération : [0.5, 0, 0.5]
coordonné de l'atome de étain après l'opération : [0, 0.5, 0.5]
______________________________________________________________________
----------------------------------------------------------------------


In [34]:
view1 = quick_view(conv_struc, conventional = "True")
display(view1)
view1.script("draw SYMOP 30 {atomno=24}") ## + 1 dans le display car liste 


JsmolView(layout=Layout(align_self='stretch', height='400px'))

### Opération de symmétrie pour l' Or 

In [44]:
s4_type : str = "Opération de rotation hélicoïdale d'ordre 4 autour de l'axe (0,1/2,0) d' (angle \pi/2) donc rotation d'odre 4 suivi d'une translation suivant l'axe c )"
print(70*'-')
print("\n Il s'agit d'une opération d'ordre deux inversant la chiralité")
print("\n Il s'agit d'une opération de :", s4_type)
print(70*'_')
print("coordonné de l'atome de {} avant l'opération : {}".format('Cesium',str(Au)))
print("coordonné de l'atome de {} avant l'opération : {}".format('Cesium',str([3/4,1/4,3/4])))
print(70*'_')
print(70*'-')

----------------------------------------------------------------------

 Il s'agit d'une opération d'ordre deux inversant la chiralité

 Il s'agit d'une opération de : Opération de rotation hélicoïdale d'ordre 4 autour de l'axe (0,1/2,0) d' (angle \pi/2) donc rotation d'odre 4 suivi d'une translation suivant l'axe c )
______________________________________________________________________
coordonné de l'atome de Cesium avant l'opération : [0.25, 0.25, 0.25]
coordonné de l'atome de Cesium avant l'opération : [0.75, 0.25, 0.75]
______________________________________________________________________
----------------------------------------------------------------------


In [50]:
view1 = quick_view(conv_struc, conventional = "True")
display(view1)
view1.script("draw SYMOP 48 {atomno=3}")


JsmolView(layout=Layout(align_self='stretch', height='400px'))

Rotation hélicoïdale par rapport à un axe hélicoïdal: $4_2$ car rotation de 90° dans le sens anti-horlogique suivi d'une translation de valeur 3/4 du vecteur de base.  